apiVersion: v1
kind: Service
metadata:
  name: neo4j-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/name: neo4j
  ports:
  - name: tcp-http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: tcp-bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: tcp-https
    port: 7473
    protocol: TCP
    targetPort: 7473
  - name: tcp-backup
    port: 6362
    protocol: TCP
    targetPort: 6362
